unpackaged/main/default/objects/Request_Type__c/Request_Type__c.object-meta.xml
<CustomObject>
    <label>Request Type</label>
    <nameField>
        <label>Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ServiceAppointment/fields/Active_Technician__c.field-meta.xml
<CustomField>
    <fullName>Active_Technician__c</fullName>
    <label>Active Technician</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Do_Not_Use_SA__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Use_SA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Use SA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Parent.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Site)</relationshipLabel>
    <relationshipName>Service_Appointments2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Parent.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Sub Customer)</relationshipLabel>
    <relationshipName>Service_Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SLA__c/SLA__c.object-meta.xml
<CustomObject>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Bill to Customer)</relationshipLabel>
    <relationshipName>Work_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Type</label>
    <referenceTo>Request_Type__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Type</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/SiteID__c.field-meta.xml
<CustomField>
    <fullName>SiteID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SLA_member__c.Sub_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SLA_member__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Sub Customer)</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <label>Vendor Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CandidateFetcherQueueableTest.cls
@isTest(SeeAllData=true)
public with sharing class CandidateFetcherQueueableTest {

    @isTest
    static void testCandidateFetcherQueueable() {
        // 1. Hardcoded IDs (Ensure these exist in your org)
        Id requestTypeId = 'a0t3h000001P6STAA0'; // Verify this exists
        Id caseId = '500OI00000KVfEnYAL';       // Verify this exists
        Id customerAccountId = '0013h00000StelgAAB'; // Verify this exists
        Id subCustomerAccountId = '0013h00000StelqAAB';// Verify this exists
        Id slaId = 'a0u3h000000WLgQAAW';        // Verify this exists
        Id slaMemberId = 'a0vOI0000050QinYAE';    // Verify this exists
        Id siteId = '0013h00000Stx8IAAR';       // Verify this exists
        Id serviceTypeId = 'a0x3h000000GgadAAC'; // Verify this exists
        Id serviceTerritoryId = '0HhOI0000000FDZ0A2'; // Verify this exists

        // Start Test
        Test.startTest();

        // **Data Setup (Focus on Minimal Requirements)**
        // 1. Create a Profile (System Administrator)
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        System.assertNotEquals(null, p, 'System Administrator profile not found');

        // 2. Create a User
        User u = new User(
            Alias = 'fsltest',
            Email = 'fsltest@example.com' + DateTime.now().getTime(), //Unique
            EmailEncodingKey = 'UTF-8',
            FirstName = 'FSL',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'fsltest@example.com' + DateTime.now().getTime() //Unique
        );
        insert u;

        // 3. Create Operating Hours
        OperatingHours oh = new OperatingHours(Name = '24x7', TimeZone = 'America/Los_Angeles');
        insert oh;

        // 4. Verify the Service Territory Exists
        List<ServiceTerritory> stList = [SELECT Id, IsActive FROM ServiceTerritory WHERE Id = :serviceTerritoryId];
        System.assert(!stList.isEmpty(), 'ServiceTerritory with ID ' + serviceTerritoryId + ' does not exist.');
        ServiceTerritory st = stList[0];

        // 5. Create a Service Resource
        ServiceResource sr = new ServiceResource(
            Name = 'Test Resource',
            IsActive = true,
            ResourceType = 'T',//Technician
            RelatedRecordId = u.Id
        );
        insert sr;

        // 6. Create a ServiceTerritoryMember
        ServiceTerritoryMember stm = new ServiceTerritoryMember(
            ServiceTerritoryId = st.Id,
            ServiceResourceId = sr.Id,
            TerritoryType = 'P',  // Primary
            EffectiveStartDate = Date.today().addDays(-1),
            EffectiveEndDate = Date.today().addYears(1)
        );
        insert stm;

        // 7. Create a WorkOrder
        WorkOrder wo = new WorkOrder(
            Sub_Customer__c = subCustomerAccountId,
            SLA__c = slaMemberId,
            Service_Type__c = serviceTypeId,
            SiteID__c = siteId,
            Bill_to_Customer__c = customerAccountId,
            Request_Type__c = requestTypeId
        );
        insert wo;

        wo.Vendor_Status__c = 'Ticket Acceptance';
        update wo;

        // 8. Create a Service Appointment
        ServiceAppointment sa = new ServiceAppointment(
            ParentRecordId = wo.Id,
            Status = 'Open',
            Work_Order__c = wo.Id,
            Bill_to_Customer__c = customerAccountId,
            Sub_Customer__c = subCustomerAccountId,
            Site__c = siteId,
            ServiceTerritoryId = st.Id, // Using hardcoded service territory ID
            Service_Type__c = serviceTypeId,
            Do_Not_Use_SA__c = true
        );
        insert sa;

        // Explicitly Enqueue the Queueable
        CandidateFetcherQueueable queueable = new CandidateFetcherQueueable(new List<Id>{sa.Id}, false);
        System.enqueueJob(queueable);

        // Stop Test
        Test.stopTest();

        // 9. Assertions
        List<AsyncApexJob> jobs = [SELECT Id, Status, ApexClass.Name FROM AsyncApexJob WHERE ApexClass.Name = 'CandidateFetcherQueueable'];
        System.assertEquals(104, jobs.size(), 'CandidateFetcherQueueable should have been enqueued.');
        System.assertEquals('Completed', jobs[0].Status, 'CandidateFetcherQueueable should have completed.');

        ServiceAppointment updatedSA = [SELECT Id, Active_Technician__c FROM ServiceAppointment WHERE Id = :sa.Id];
        System.assertNotEquals(null, updatedSA.Active_Technician__c, 'Active_Technician__c should be populated by CandidateFetcherQueueable.');

        System.debug('Updated Service Appointment: ' + updatedSA);
    }
}