unpackaged/main/default/objects/Group__mdt/Group__mdt.object-meta.xml
<CustomObject>
    <label>Group</label>
    <pluralLabel>Groups</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Group__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object_Setting__mdt</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/Group__mdt/fields/SelectFields__c.field-meta.xml
<CustomField>
    <fullName>SelectFields__c</fullName>
    <label>Select Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Object_Setting__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Outgoing_Message__c/Outgoing_Message__c.object-meta.xml
<CustomObject>
    <label>Outgoing Message</label>
    <nameField>
        <displayFormat>OGM-{0000}</displayFormat>
        <label>Outgoing Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outgoing Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/JsonMessageCreator.cls
/**
* @author Tal Licht
* @date 2020-08-19
* @description JSON creator for the message body
*/
global with sharing class JsonMessageCreator implements MessageCreatorInterface{

    public String createMessage(Outgoing_Message__c masterOgm, Set<Id> childOgms, String groupName, String param2) {
        Id objId = masterOgm.Id;
        return serializeMessage(objId, objId.getSObjectType().getDescribe().getName(), groupName);
    }

    public String createMessage(Id objId, String objType, Set<Id> childOgms, String groupName, String param2) {
        return serializeMessage(objId, objType, groupName);
    }

    public String serializeMessage(Id objId, String objType, String groupName) {
        String fieldsToQuery = String.valueOf([SELECT SelectFields__c FROM Group__mdt WHERE Object__r.ObjectName__c = :objType AND DeveloperName = :groupName][0].SelectFields__c );
        String q = 'SELECT ' + fieldsToQuery + ' FROM ' + objType + ' WHERE id = \'' + objId + '\'';
        List<SObject> sobjList = Database.query(q);
        if (sobjList.size() > 0) {
            return JSON.serialize(sobjList.get(0));
        }
        return null;
    }
}