unpackaged/main/default/objects/Account/fields/Bill_to_customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Site_ID_number__c.field-meta.xml
<CustomField>
    <fullName>Site_ID_number__c</fullName>
    <label>Site ID number</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Bill_to_Customer.recordType-meta.xml
<RecordType>
    <fullName>Bill_to_Customer</fullName>
    <active>true</active>
    <description>A parent Account of all Sub Customers that belong to the same Customer</description>
    <label>Bill to Customer</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>A place where actual work is performed</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Sub_Customer.recordType-meta.xml
<RecordType>
    <fullName>Sub_Customer</fullName>
    <active>true</active>
    <description>A type of Account that stores SLAs, Skills and other information applicable to all Sites that belong to a Sub Customer</description>
    <label>Sub Customer</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Bill_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Bill To Customer)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Type</label>
    <referenceTo>Request_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Requestor_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>Requestor_E_Mail__c</fullName>
    <label>Requestor E-Mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Sub Customer)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Request_Type__c/Request_Type__c.object-meta.xml
<CustomObject>
    <label>Request Type</label>
    <nameField>
        <label>Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Type__c/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contract ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Service Types</relationshipLabel>
    <relationshipName>Service_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Type__c/fields/Duration_in__c.field-meta.xml
<CustomField>
    <fullName>Duration_in__c</fullName>
    <label>Duration In:</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Type__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Job Type</value>
        </filterItems>
        <filterItems>
            <field>Service_Type__c.Contract_ID__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_ID__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Service Types (Job Type)</relationshipLabel>
    <relationshipName>Service_Types1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Type__c/recordTypes/Contract_ID.recordType-meta.xml
<RecordType>
    <fullName>Contract_ID</fullName>
    <active>true</active>
    <label>Contract ID</label>
</RecordType>

unpackaged/main/default/objects/Service_Type__c/recordTypes/Job_Type.recordType-meta.xml
<RecordType>
    <fullName>Job_Type</fullName>
    <active>true</active>
    <label>Job Type</label>
</RecordType>

unpackaged/main/default/objects/Service_Type__c/recordTypes/Service_Type.recordType-meta.xml
<RecordType>
    <fullName>Service_Type</fullName>
    <active>true</active>
    <label>Service Type</label>
</RecordType>

unpackaged/main/default/objects/SLA__c/SLA__c.object-meta.xml
<CustomObject>
    <label>SLA</label>
    <nameField>
        <label>SLA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SLA__c/fields/Priority_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Priority_Code_ID__c</fullName>
    <label>Priority_Code_ID</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SLA_member__c/SLA_member__c.object-meta.xml
<CustomObject>
    <label>SLA member</label>
    <nameField>
        <label>SLA member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLA members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SLA_member__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <referenceTo>SLA__c</referenceTo>
    <relationshipLabel>SLA members</relationshipLabel>
    <relationshipName>SLA_members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SLA_member__c/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLA members</relationshipLabel>
    <relationshipName>SLA_members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Bill to Customer)</relationshipLabel>
    <relationshipName>Work_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Contract_ID__c.field-meta.xml
<CustomField>
    <fullName>Contract_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Contract ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Work Orders (Contract ID)</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Job Type</value>
        </filterItems>
        <filterItems>
            <field>Service_Type__c.Contract_ID__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contract_ID__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Work Orders (Job Type)</relationshipLabel>
    <relationshipName>Work_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Type</label>
    <referenceTo>Request_Type__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Requestor_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>Requestor_E_Mail__c</fullName>
    <label>Requestor E-Mail</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Type</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/SiteID__c.field-meta.xml
<CustomField>
    <fullName>SiteID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SLA_member__c.Sub_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SLA_member__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Sub Customer)</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TestFactory.cls
public with sharing class TestFactory {
    public static WorkOrder createWorkOrder(Id caseId, Id slaId, Id subCustomerId, Id serviceTypeId, Id siteId, Id billToCustomerId, Id requestTypeId) {
        WorkOrder wo = new WorkOrder();
        wo.CaseId = caseId;
        wo.Sub_Customer__c = subCustomerId;
        wo.SLA__c = slaId;
        wo.Service_Type__c = serviceTypeId;
        wo.SiteID__c = siteId;
        wo.Bill_to_Customer__c = billToCustomerId;
        wo.Request_Type__c = requestTypeId;
        return wo;
    }

    public static Case createCase(String subject, Id requestTypeId, String email) {
        Case cs = new Case();
        cs.Subject = subject;
        cs.Status = 'Open';
        cs.Request_Type__c = requestTypeId;
        cs.Requestor_E_Mail__c = email;

        return cs;
    }

    public static Request_Type__c createRequestType(String name) {
        Request_Type__c requestType = new Request_Type__c();
        requestType.Name = name;
        
        return requestType;
    }
    
    public static Account createSite(String name, String siteIdNumber, Id subCustomerId, String street, String city, String country, String state, String postalCode) {
        Account site = new Account();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Site').getRecordTypeId();
        site.RecordTypeId = recordTypeId;
        site.Name = name;
        site.Site_ID_number__c = siteIdNumber;
        site.ParentId = subCustomerId;
        site.BillingStreet = street;
        site.BillingCity = city;
        site.BillingCountry = country;
        site.BillingState = state;
        site.BillingPostalCode = postalCode;
        
        return site;
    }

    public static Account createCustomer(String name) {
        Account customer = new Account();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Bill_to_Customer').getRecordTypeId();
        customer.RecordTypeId = recordTypeId;
        customer.Name = name;
        
        return customer;
    }

    public static Account createSubCustomer(String name, Id parentAccountId) {
        Account subCustomer = new Account();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Sub_Customer').getRecordTypeId();
        subCustomer.RecordTypeId = recordTypeId;
        subCustomer.ParentId = parentAccountId;
        subCustomer.Name = name;
        
        return subCustomer;
    }

    public static SLA_member__c createSLAMember(String name, Id subCustomerId, Id SLAId) {
        SLA_member__c SLAMember = new SLA_member__c();

        SLAMember.Name = name;
        SLAMember.SLA__c = SLAId;
        SLAMember.Sub_Customer__c = subCustomerId;
        
        return SLAMember;
    }

    public static SLA__c createSLA(String name, Integer priority, String priorityCodeID) {
        SLA__c SLA = new SLA__c();

        SLA.Name = name;
        SLA.Priority__c = priority;
        SLA.Priority_Code_ID__c = priorityCodeID;
        
        return SLA;
    }

    public static Service_Type__c createServiceType(String name, Integer duration, Id jobTypeId, Id contractId) {
        Service_Type__c serviceType = new Service_Type__c();

        Id recordTypeId = Schema.SObjectType.Service_Type__c.getRecordTypeInfosByDeveloperName().get('Service_Type').getRecordTypeId();
        serviceType.Name = name;
        serviceType.RecordTypeId = recordTypeId;
        serviceType.Duration__c = duration;
        serviceType.Duration_in__c = 'Minutes';
        serviceType.Job_Type__c = jobTypeId;
        serviceType.Contract_ID__c = contractId;

        return serviceType;
    }

    public static Service_Type__c createJobType(String name, Id contractId) {
        Service_Type__c jobType = new Service_Type__c();

        Id recordTypeId = Schema.SObjectType.Service_Type__c.getRecordTypeInfosByDeveloperName().get('Job_Type').getRecordTypeId();
        jobType.Name = name;
        jobType.RecordTypeId = recordTypeId;
        jobType.Contract_ID__c = contractId;

        return jobType;
    }

    public static Service_Type__c createContract(String name) {
        Service_Type__c contract = new Service_Type__c();

        Id recordTypeId = Schema.SObjectType.Service_Type__c.getRecordTypeInfosByDeveloperName().get('Contract_ID').getRecordTypeId();
        contract.Name = name;
        contract.RecordTypeId = recordTypeId;
        
        return contract;
    }
}