unpackaged/main/default/objects/Account/fields/Bill_to_customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>A place where actual work is performed</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Bill_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Bill To Customer)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Type</label>
    <referenceTo>Request_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Sub Customer)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MaintenancePlan/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Maintenance Plans (Bill to Customer)</relationshipLabel>
    <relationshipName>Maintenance_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MaintenancePlan/fields/Desired_Arrival_Window_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Desired_Arrival_Window_End_Time__c</fullName>
    <label>Desired Arrival Window End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/MaintenancePlan/fields/Desired_Arrival_Window_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Desired_Arrival_Window_Start_Time__c</fullName>
    <label>Desired Arrival Window Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/MaintenancePlan/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Type</label>
    <referenceTo>Request_Type__c</referenceTo>
    <relationshipLabel>Maintenance Plans</relationshipLabel>
    <relationshipName>Maintenance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MaintenancePlan/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Type</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Maintenance Plans</relationshipLabel>
    <relationshipName>Maintenance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MaintenancePlan/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SLA_member__c.Sub_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SLA_member__c</referenceTo>
    <relationshipLabel>Maintenance Plans</relationshipLabel>
    <relationshipName>Maintenance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MaintenancePlan/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Maintenance Plans</relationshipLabel>
    <relationshipName>Maintenance_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Parent.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Sub Customer)</relationshipLabel>
    <relationshipName>Service_Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SLA_member__c/SLA_member__c.object-meta.xml
<CustomObject>
    <label>SLA member</label>
    <nameField>
        <label>SLA member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLA members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SLA_member__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <referenceTo>SLA__c</referenceTo>
    <relationshipLabel>SLA members</relationshipLabel>
    <relationshipName>SLA_members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SLA_member__c/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SLA members</relationshipLabel>
    <relationshipName>SLA_members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Bill to Customer)</relationshipLabel>
    <relationshipName>Work_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Type</label>
    <referenceTo>Request_Type__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Type</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SLA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SLA_member__c.Sub_Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SLA_member__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Sub Customer)</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EnablePreventGeocodeChatterTest.cls
@isTest
private class EnablePreventGeocodeChatterTest {
      @TestSetup
    static void makeData() {
       Request_Type__c requestType = TestFactory.createRequestType('Test Request Type');
        insert requestType;

        Case cs = TestFactory.createCase('Test', requestType.Id, 'test@test.com');
        insert cs;

        TimeZone timeZone = UserInfo.getTimeZone();
        OperatingHours operatingHours = new OperatingHours(Name = 'Test', TimeZone = timeZone.toString());
        insert operatingHours;

        Service_Type__c contract = TestFactory.createContract('Test Contract');
        insert contract;

        Service_Type__c jobType = TestFactory.createJobType('Test Job Type', contract.Id);
        insert jobType;

        Service_Type__c serviceType = TestFactory.createServiceType('Test Service Type', 60, jobType.Id, contract.Id);
        insert serviceType;

        Account customer = TestFactory.createCustomer('Test Customer');
        insert customer;

        Account subCustomer = TestFactory.createSubCustomer('Test Sub Customer', customer.Id);
        insert subCustomer;

        SLA__c sla = TestFactory.createSLA('Test SLA', 1, '4');
        insert sla;

        SLA_member__c slaMember = TestFactory.createSLAMember('Test SLA Member', subCustomer.Id, sla.Id);
        insert slaMember;

        Account site = TestFactory.createSite('Test Site', '4', subCustomer.Id, '2800 East 1st Avenue', 'Vancouver', 'Canada', 'BC', 'V5M 4N9');
        insert site;
}

    // Test case to cover the scenario where all geolocation fields and assigned technician are null
    @isTest
    static void testAllFieldsNull() {
         Case cs = [SELECT Id FROM Case];
        SLA_member__c slaMember = [SELECT Id FROM SLA_member__c];
        Account customer = [SELECT Id FROM Account WHERE Name = 'Test Customer'];
        Account subCustomer = [SELECT Id FROM Account WHERE Name = 'Test Sub Customer'];
        Service_Type__c serviceType = [SELECT Id FROM Service_Type__c WHERE Name = 'Test Service Type'];
        Account site = [SELECT Id FROM Account WHERE Name = 'Test Site'];
        OperatingHours operatingHours = [SELECT Id FROM OperatingHours WHERE Name = 'Test'];
        Request_Type__c requestType = [SELECT Id FROM Request_Type__c WHERE Name = 'Test Request Type'];
        
        MaintenancePlan maintenancePlan = new MaintenancePlan();
        maintenancePlan.Frequency = 1;
        maintenancePlan.StartDate = Date.today();
        maintenancePlan.NextSuggestedMaintenanceDate = Date.today().addDays(2);
        maintenancePlan.GenerationTimeframe = 1;
        maintenancePlan.Desired_Arrival_Window_Start_Time__c = Time.newInstance(17, 0, 0, 0);
        maintenancePlan.Desired_Arrival_Window_End_Time__c = Time.newInstance(18, 0, 0, 0);
        maintenancePlan.Service_Type__c = serviceType.Id;
        maintenancePlan.SLA__c = slaMember.Id;
        maintenancePlan.Bill_to_Customer__c = customer.Id;
        maintenancePlan.Sub_Customer__c = subCustomer.Id;
        maintenancePlan.Site__c = site.Id;

        insert maintenancePlan;
        
        WorkOrder wo = TestFactory.createWorkOrder(cs.Id, slaMember.Id, subCustomer.Id, serviceType.Id, site.Id, customer.Id, requestType.Id);
        wo.MaintenancePlanId = maintenancePlan.Id;
        wo.SuggestedMaintenanceDate = Date.today();
        insert wo;
        
        ServiceTerritory serviceTerritory = new ServiceTerritory(Name= '02 Toronto', OperatingHoursId = operatingHours.Id, IsActive=true);
        insert serviceTerritory;
        
        Account account = new Account(Name = 'Test');
        insert account;


    ServiceAppointment serviceAppointment = new ServiceAppointment();
    serviceAppointment.ParentRecordId = wo.Id;
    serviceAppointment.Work_Order__c = wo.Id;
    serviceAppointment.Status = '01 Open';
    serviceAppointment.EarliestStartTime = DateTime.now();
    serviceAppointment.DueDate = Date.today().addDays(2);
    serviceAppointment.Street = '301 Bottomley Avenue North';
    serviceAppointment.State = 'Saskatchewan';
    serviceAppointment.PostalCode = 'S7N 1L3';
    serviceAppointment.Country = 'Canada';
    serviceAppointment.City = 'Saskatoon';
    serviceAppointment.Bill_to_Customer__c = customer.Id;
    serviceAppointment.ETA__c = 30; // Set an example ETA value in minutes (e.g., 30 minutes).

    // Make sure to set the Enroute_Time_Stamp__c field to a valid value in your data setup.
    serviceAppointment.Enroute_Time_Stamp__c = DateTime.now();

    // Insert the ServiceAppointment record within the Test.startTest() and Test.stopTest() block
    
    //insert serviceAppointment;
        
        // Insert the ServiceAppointment
        Test.startTest();
        insert serviceAppointment;
        Test.stopTest();
        
        // Retrieve the inserted ServiceAppointment
        serviceAppointment = [SELECT FSL__Prevent_Geocoding_For_Chatter_Actions__c FROM ServiceAppointment WHERE Id = :serviceAppointment.Id];
        
        // Verify that the FSL__Prevent_Geocoding_For_Chatter_Actions__c field is true
        System.assertEquals(true, serviceAppointment.FSL__Prevent_Geocoding_For_Chatter_Actions__c);
    }

    // Test case to cover the scenario where at least one geolocation field is populated
    @isTest
    static void testSomeFieldsPopulated() {
        Case cs = [SELECT Id FROM Case];
        SLA_member__c slaMember = [SELECT Id FROM SLA_member__c];
        Account customer = [SELECT Id FROM Account WHERE Name = 'Test Customer'];
        Account subCustomer = [SELECT Id FROM Account WHERE Name = 'Test Sub Customer'];
        Service_Type__c serviceType = [SELECT Id FROM Service_Type__c WHERE Name = 'Test Service Type'];
        Account site = [SELECT Id FROM Account WHERE Name = 'Test Site'];
        OperatingHours operatingHours = [SELECT Id FROM OperatingHours WHERE Name = 'Test'];
        Request_Type__c requestType = [SELECT Id FROM Request_Type__c WHERE Name = 'Test Request Type'];
        
        MaintenancePlan maintenancePlan = new MaintenancePlan();
        maintenancePlan.Frequency = 1;
        maintenancePlan.StartDate = Date.today();
        maintenancePlan.NextSuggestedMaintenanceDate = Date.today().addDays(2);
        maintenancePlan.GenerationTimeframe = 1;
        maintenancePlan.Desired_Arrival_Window_Start_Time__c = Time.newInstance(17, 0, 0, 0);
        maintenancePlan.Desired_Arrival_Window_End_Time__c = Time.newInstance(18, 0, 0, 0);
        maintenancePlan.Service_Type__c = serviceType.Id;
        maintenancePlan.SLA__c = slaMember.Id;
        maintenancePlan.Bill_to_Customer__c = customer.Id;
        maintenancePlan.Sub_Customer__c = subCustomer.Id;
        maintenancePlan.Site__c = site.Id;

        insert maintenancePlan;
        
        WorkOrder wo = TestFactory.createWorkOrder(cs.Id, slaMember.Id, subCustomer.Id, serviceType.Id, site.Id, customer.Id, requestType.Id);
        wo.MaintenancePlanId = maintenancePlan.Id;
        wo.SuggestedMaintenanceDate = Date.today();
        insert wo;
        
        ServiceTerritory serviceTerritory = new ServiceTerritory(Name= '02 Toronto', OperatingHoursId = operatingHours.Id, IsActive=true);
        insert serviceTerritory;
        
        Account account = new Account(Name = 'Test');
        insert account;


    ServiceAppointment sa = new ServiceAppointment();
    sa.ParentRecordId = wo.Id;
    sa.Work_Order__c = wo.Id;
    sa.Status = '01 Open';
    sa.EarliestStartTime = DateTime.now();
    sa.DueDate = Date.today().addDays(2);
    sa.Street = '301 Bottomley Avenue North';
    sa.State = 'Saskatchewan';
    sa.PostalCode = 'S7N 1L3';
    sa.Country = 'Canada';
    sa.City = 'Saskatoon';
    sa.FSL__InternalSLRGeolocation__Latitude__s = 37.7749;
    sa.FSL__InternalSLRGeolocation__Longitude__s = -122.4194;
    sa.Bill_to_Customer__c = customer.Id;
    sa.ETA__c = 30; // Set an example ETA value in minutes (e.g., 30 minutes).

    // Make sure to set the Enroute_Time_Stamp__c field to a valid value in your data setup.
    sa.Enroute_Time_Stamp__c = DateTime.now();

    // Insert the ServiceAppointment record within the Test.startTest() and Test.stopTest() block
    
    //insert serviceAppointment;
       
        
        // Insert the ServiceAppointment
        Test.startTest();
        insert sa;
        Test.stopTest();
        
        // Retrieve the inserted ServiceAppointment
        sa = [SELECT FSL__Prevent_Geocoding_For_Chatter_Actions__c FROM ServiceAppointment WHERE Id = :sa.Id];
        
        // Verify that the FSL__Prevent_Geocoding_For_Chatter_Actions__c field is null
    //    System.assertEquals(null, sa.FSL__Prevent_Geocoding_For_Chatter_Actions__c);
    }

    
}