unpackaged/main/default/objects/Account/fields/Bill_to_customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Send_Potential_Tech__c.field-meta.xml
<CustomField>
    <fullName>Send_Potential_Tech__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field will be used to Trigger the CandidateFetcherQueueable class. If the Checkbox is true, the trigger will run and get the Activate candidate on SA</description>
    <label>Send Potential Tech</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ServiceAppointment/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Do_Not_Use_SA__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Use_SA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Use SA</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Open Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Reference1__c.field-meta.xml
<CustomField>
    <fullName>Reference1__c</fullName>
    <label>Reference1</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Schedule_Automatically__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Automatically__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Schedule Automatically</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.Parent.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Site)</relationshipLabel>
    <relationshipName>Service_Appointments2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.Parent.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments (Sub Customer)</relationshipLabel>
    <relationshipName>Service_Appointments1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Bill_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Bill to Customer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Bill to Customer)</relationshipLabel>
    <relationshipName>Work_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Open Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Reference1__c.field-meta.xml
<CustomField>
    <fullName>Reference1__c</fullName>
    <label>Reference1</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service_Type__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Type</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/SiteID__c.field-meta.xml
<CustomField>
    <fullName>SiteID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Sub_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sub_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_to_Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Sub Customer)</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <label>Vendor Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ServiceAppointmentUtility.cls
public class ServiceAppointmentUtility {
    // Method to create Service Appointments
    public static List<ServiceAppointment> createServiceAppointments(List<WorkOrder> workOrders) {
        List<ServiceAppointment> saToCreate = new List<ServiceAppointment>();
        Set<Id> accountIds = new Set<Id>();

        // Collect Account IDs for validation
        for (WorkOrder wo : workOrders) {
            if (wo.Bill_to_Customer__c != null) accountIds.add(wo.Bill_to_Customer__c);
            if (wo.Sub_Customer__c != null) accountIds.add(wo.Sub_Customer__c);
        }

        // Query Accounts
        Map<Id, Account> accountMap = new Map<Id, Account>([
            SELECT Id, Name, Send_Potential_Tech__c 
            FROM Account 
            WHERE Id IN :accountIds
        ]);

        // Create Service Appointments
        for (WorkOrder wo : workOrders) {
            Account subCustomerAccount = accountMap.get(wo.Sub_Customer__c);

            // Check if Vendor Status contains 'Ticket Acceptance'
            Boolean isVendorStatusValid = (wo.Vendor_Status__c != null && 
                                         wo.Vendor_Status__c.contains('Ticket Acceptance'));

            if (subCustomerAccount != null && 
                subCustomerAccount.Send_Potential_Tech__c == TRUE && 
                isVendorStatusValid) {

                ServiceAppointment sa = new ServiceAppointment();
                sa.ParentRecordId = wo.Id;
                sa.EarliestStartTime = System.now().addHours(2);
                sa.DueDate = System.today().addDays(14);
                sa.Status = 'Open';
                sa.Work_Order__c = wo.Id;
                sa.Bill_to_Customer__c = wo.Bill_to_Customer__c;
                sa.Sub_Customer__c = wo.Sub_Customer__c;
                sa.Site__c = wo.SiteID__c;
                sa.Duration = wo.Duration;
                sa.ServiceTerritoryId = wo.ServiceTerritoryId;
                sa.Service_Type__c = wo.Service_Type__c;
                sa.Open_Date__c = wo.Open_Date__c;
                sa.Schedule_Automatically__c = false;    
                sa.Reference1__c = wo.Reference1__c;
                sa.Do_Not_Use_SA__c = true;

                saToCreate.add(sa);
            }
        }
        return saToCreate;
    }

    // Handle post-creation logic
    public static void handlePostCreation(List<ServiceAppointment> saToCreate) {
        if (!saToCreate.isEmpty()) {
            try {
                insert saToCreate;
                List<Id> createdSAIds = new List<Id>();
                for (ServiceAppointment sa : saToCreate) {
                    createdSAIds.add(sa.Id);
                }
                System.debug('Created ' + saToCreate.size() + ' Service Appointments');

                // Schedule initial check after 10 minutes
                scheduleDeletionCheck(createdSAIds);

                // Enqueue CandidateFetcherQueueable
                System.enqueueJob(new CandidateFetcherQueueable(createdSAIds, true));
            } catch (DmlException e) {
                System.debug('SA creation error: ' + e.getMessage());
            }
        }
    }

    // Schedule initial deletion check
    private static void scheduleDeletionCheck(List<Id> saIds) {
        Datetime scheduleTime = System.now().addMinutes(10);
        String cronExpression = 
            scheduleTime.second() + ' ' + 
            scheduleTime.minute() + ' ' + 
            scheduleTime.hour() + ' ' + 
            scheduleTime.day() + ' ' + 
            scheduleTime.month() + ' ? ' + 
            scheduleTime.year();

        System.schedule(
            'SACheck_' + System.currentTimeMillis(),
            cronExpression,
            new DeleteTempSAJob(saIds)
        );
    }
}