unpackaged/main/default/objects/Case/fields/Keywords_Found__c.field-meta.xml
<CustomField>
    <fullName>Keywords_Found__c</fullName>
    <label>Keywords Found</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Match_Found__c.field-meta.xml
<CustomField>
    <fullName>Match_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Match Found</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Matched_Queues__c.field-meta.xml
<CustomField>
    <fullName>Matched_Queues__c</fullName>
    <label>Matched Queues</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Queue_Type__c.field-meta.xml
<CustomField>
    <fullName>Queue_Type__c</fullName>
    <label>Queue Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Routing_Rule_Link__c.field-meta.xml
<CustomField>
    <fullName>Routing_Rule_Link__c</fullName>
    <label>Routing Rule Link</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Rule_Found__c.field-meta.xml
<CustomField>
    <fullName>Rule_Found__c</fullName>
    <label>Rule Found</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/SubCustomer_Match__c.field-meta.xml
<CustomField>
    <fullName>SubCustomer_Match__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SubCustomer Match</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/SubCustomer_Name__c.field-meta.xml
<CustomField>
    <fullName>SubCustomer_Name__c</fullName>
    <label>SubCustomer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Routing_Rule__c/Routing_Rule__c.object-meta.xml
<CustomObject>
    <label>Routing Rule</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Routing Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Routing_Rule__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CC Address</fullName>
            </value>
            <value>
                <fullName>Description</fullName>
            </value>
            <value>
                <fullName>From Address</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>To Address</fullName>
            </value>
            <value>
                <fullName>Text Body</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Routing_Rule__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Starts With</fullName>
            </value>
            <value>
                <fullName>Does Not Contain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Routing_Rule__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 HR MTTR</fullName>
            </value>
            <value>
                <fullName>24 HR MTTR</fullName>
            </value>
            <value>
                <fullName>4 HR MTTR</fullName>
            </value>
            <value>
                <fullName>ADMIN</fullName>
            </value>
            <value>
                <fullName>Best Effort</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Manager Request</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>MTTR</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Starbucks</fullName>
            </value>
            <value>
                <fullName>Taco Bell</fullName>
            </value>
            <value>
                <fullName>Travel Zone 1</fullName>
            </value>
            <value>
                <fullName>Travel Zone 2</fullName>
            </value>
            <value>
                <fullName>Travel Zone 3</fullName>
            </value>
            <value>
                <fullName>Travel Zone 4</fullName>
            </value>
            <value>
                <fullName>Travel Zone 5</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>US - Regional Manager Request</fullName>
            </value>
            <value>
                <fullName>US - Site Survey</fullName>
            </value>
            <value>
                <fullName>US - Tech Request</fullName>
            </value>
            <value>
                <fullName>US - Vendor Required</fullName>
            </value>
            <value>
                <fullName>US - Zayo</fullName>
            </value>
            <value>
                <fullName>VIASAT - PMs</fullName>
            </value>
            <value>
                <fullName>Viasat Sev 1</fullName>
            </value>
            <value>
                <fullName>Viasat Sev 2</fullName>
            </value>
            <value>
                <fullName>Viasat Sev 3</fullName>
            </value>
            <value>
                <fullName>Viasat Sev 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Routing_Rule__c/fields/Queue_Type__c.field-meta.xml
<CustomField>
    <fullName>Queue_Type__c</fullName>
    <label>Queue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Auto_Close</fullName>
            </value>
            <value>
                <fullName>Bell_Locates_Queue</fullName>
            </value>
            <value>
                <fullName>CBTS</fullName>
            </value>
            <value>
                <fullName>Comcast</fullName>
            </value>
            <value>
                <fullName>CSCEmails</fullName>
            </value>
            <value>
                <fullName>Dispatcher_Queue_for_In_Jeopardy</fullName>
            </value>
            <value>
                <fullName>EmailQue</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>GeneralQueue</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>kywired_alarm_report</fullName>
            </value>
            <value>
                <fullName>LocatesQue</fullName>
            </value>
            <value>
                <fullName>MTTR</fullName>
            </value>
            <value>
                <fullName>Overflow</fullName>
            </value>
            <value>
                <fullName>Pending_Vendor_Scheduling</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Resource_Planning</fullName>
            </value>
            <value>
                <fullName>Service_Email</fullName>
            </value>
            <value>
                <fullName>Service_Phone</fullName>
            </value>
            <value>
                <fullName>Spectrum</fullName>
            </value>
            <value>
                <fullName>Telus</fullName>
            </value>
            <value>
                <fullName>Tier2</fullName>
            </value>
            <value>
                <fullName>Valley_Fiber_Skill</fullName>
            </value>
            <value>
                <fullName>Vendor_Scheduled</fullName>
            </value>
            <value>
                <fullName>Viasat_PM</fullName>
            </value>
            <value>
                <fullName>Zayo</fullName>
            </value>
            <value>
                <fullName>ZayoMTTR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Routing_Rule__c/fields/Routing_Rule_Group__c.field-meta.xml
<CustomField>
    <fullName>Routing_Rule_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Routing Rule Group</label>
    <referenceTo>Routing_Rule_Group__c</referenceTo>
    <relationshipLabel>Routing Rules</relationshipLabel>
    <relationshipName>Routing_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Routing_Rule__c/fields/SubCustomer__c.field-meta.xml
<CustomField>
    <fullName>SubCustomer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubCustomer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Routing Rules</relationshipLabel>
    <relationshipName>Routing_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Routing_Rule_Group__c/Routing_Rule_Group__c.object-meta.xml
<CustomObject>
    <label>Routing Rule Group</label>
    <nameField>
        <label>Routing Rule Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routing Rule Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Routing_Rule_Group__c/fields/Logic_Type__c.field-meta.xml
<CustomField>
    <fullName>Logic_Type__c</fullName>
    <label>Logic Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CaseRoutingHandler.cls
public class CaseRoutingHandler {
    
    // Recursion guard
    public static Boolean isFirstRun = true;
    
    public static void processAndRoute(List<Case> newCases, Map<Id, Case> oldMap) {
        
        if (!isFirstRun) return;
        isFirstRun = false;
        
        if (newCases == null || newCases.isEmpty()) return;
        
        try {
            // Collect case Ids
            Set<Id> caseIds = new Set<Id>();
            for (Case c : newCases) {
                caseIds.add(c.Id);
            }
            
            // Get active routing groups + child rules, sorted by priority (lowest number = highest priority)
            List<Routing_Rule_Group__c> ruleGroups = [
                SELECT Id, Name, Logic_Type__c, Priority__c,
                    (SELECT Id, Name, Criteria__c, Operator__c, Value__c, Domain__c,
                            Queue_Type__c, SubCustomer__c, SubCustomer__r.Name,
                            Active__c, Routing_Rule_Group__c
                     FROM Routing_Rules__r
                     WHERE Active__c = TRUE
                     ORDER BY Priority__c ASC NULLS LAST)
                FROM Routing_Rule_Group__c
                WHERE Active__c = TRUE
                ORDER BY Priority__c ASC NULLS LAST
            ];
            
            // Get related Email Messages
            Map<Id, List<EmailMessage>> caseEmailMap = new Map<Id, List<EmailMessage>>();
            for (EmailMessage em : [
                SELECT Id, ParentId, FromAddress, ToAddress, CcAddress, 
                       Subject, TextBody, HtmlBody, Headers
                FROM EmailMessage
                WHERE ParentId IN :caseIds
                ORDER BY CreatedDate DESC
            ]) {
                if (!caseEmailMap.containsKey(em.ParentId)) {
                    caseEmailMap.put(em.ParentId, new List<EmailMessage>());
                }
                caseEmailMap.get(em.ParentId).add(em);
            }
            
            List<Case> casesToUpdate = new List<Case>();
            
            for (Case c : newCases) {
                
                Boolean matchFound = false;
                Set<String> matchedKeywords  = new Set<String>();
                Set<String> matchedRuleNames = new Set<String>();
                Set<String> matchedQueues    = new Set<String>();
                Set<String> matchedRuleLinks = new Set<String>();
                
                String determinedQueueType = null;
                Id matchedSubCustomerId = null;
                String matchedSubCustomerName = null;
                
                List<EmailMessage> caseEmails = caseEmailMap.get(c.Id) != null 
                    ? caseEmailMap.get(c.Id) 
                    : new List<EmailMessage>();
                
                // Evaluate groups in priority order
                for (Routing_Rule_Group__c groupRule : ruleGroups) {
                    
                    if (groupRule.Routing_Rules__r == null || groupRule.Routing_Rules__r.isEmpty()) {
                        continue;
                    }
                    
                    Boolean groupMatched = false;
                    Set<String> tempKeywords = new Set<String>();
                    List<String> groupMatchedRuleLinks = new List<String>();
                    
                    String logicType = String.isBlank(groupRule.Logic_Type__c) 
                        ? 'AND' 
                        : groupRule.Logic_Type__c.trim().toUpperCase();
                    
                    if (logicType == 'OR') {
                        // OR logic: at least one rule must match
                        for (Routing_Rule__c rule : groupRule.Routing_Rules__r) {
                            if (evaluateRule(rule, c, caseEmails)) {
                                groupMatched = true;
                                
                                if (String.isNotBlank(rule.Value__c)) tempKeywords.add(rule.Value__c);
                                if (String.isNotBlank(rule.Domain__c)) tempKeywords.add(rule.Domain__c);
                                
                                groupMatchedRuleLinks.add('<a href="/' + rule.Id + '">' + rule.Name + '</a>');
                                
                                if (String.isNotBlank(rule.Queue_Type__c)) {
                                    matchedQueues.add(rule.Queue_Type__c);
                                    determinedQueueType = rule.Queue_Type__c;
                                }
                                if (rule.SubCustomer__c != null) {
                                    matchedSubCustomerId = rule.SubCustomer__c;
                                    matchedSubCustomerName = rule.SubCustomer__r?.Name;
                                }
                            }
                        }
                    } else {
                        // AND logic: all rules must match
                        groupMatched = true;
                        for (Routing_Rule__c rule : groupRule.Routing_Rules__r) {
                            if (!evaluateRule(rule, c, caseEmails)) {
                                groupMatched = false;
                                break;
                            }
                            
                            if (String.isNotBlank(rule.Value__c)) tempKeywords.add(rule.Value__c);
                            if (String.isNotBlank(rule.Domain__c)) tempKeywords.add(rule.Domain__c);
                            
                            groupMatchedRuleLinks.add('<a href="/' + rule.Id + '">' + rule.Name + '</a>');
                            
                            if (String.isNotBlank(rule.Queue_Type__c)) {
                                matchedQueues.add(rule.Queue_Type__c);
                                determinedQueueType = rule.Queue_Type__c;
                            }
                            if (rule.SubCustomer__c != null) {
                                matchedSubCustomerId = rule.SubCustomer__c;
                                matchedSubCustomerName = rule.SubCustomer__r?.Name;
                            }
                        }
                    }
                    
                    // If this group matched → take its results and STOP (highest priority wins)
                    if (groupMatched) {
                        matchFound = true;
                        matchedKeywords.addAll(tempKeywords);
                        matchedRuleNames.add(groupRule.Name);
                        matchedRuleLinks.addAll(groupMatchedRuleLinks);
                        
                        // Break here - we take the first (highest priority) matching group
                        break;
                    }
                }
                
                // Prepare update
                Case caseUpdate = new Case(Id = c.Id);
                Boolean hasChanges = false;
                
                if (c.Match_Found__c != matchFound) {
                    caseUpdate.Match_Found__c = matchFound;
                    hasChanges = true;
                }
                
                String keywordsText = matchedKeywords.isEmpty() ? 'No Keyword Found' 
                                    : String.join(new List<String>(matchedKeywords), ', ');
                if (c.Keywords_Found__c != keywordsText) {
                    caseUpdate.Keywords_Found__c = keywordsText;
                    hasChanges = true;
                }
                
                String rulesText = String.join(new List<String>(matchedRuleNames), ', ');
                if (rulesText.length() > 255) rulesText = rulesText.substring(0, 255);
                if (c.Rule_Found__c != rulesText) {
                    caseUpdate.Rule_Found__c = rulesText;
                    hasChanges = true;
                }
                
                String linksText = String.join(new List<String>(matchedRuleLinks), ' | ');
                if (c.Routing_Rule_Link__c != linksText) {
                    caseUpdate.Routing_Rule_Link__c = linksText;
                    hasChanges = true;
                }
                
                String queuesText = String.join(new List<String>(matchedQueues), ', ');
                if (c.Matched_Queues__c != queuesText) {
                    caseUpdate.Matched_Queues__c = queuesText;
                    hasChanges = true;
                }
                
                if (determinedQueueType != null && c.Queue_Type__c != determinedQueueType) {
                    caseUpdate.Queue_Type__c = determinedQueueType;
                    hasChanges = true;
                }
                
                // Sub-customer logic
                if (matchedSubCustomerId != null && String.isNotBlank(matchedSubCustomerName)) {
                    if (c.SubCustomer_Name__c != matchedSubCustomerName) {
                        caseUpdate.SubCustomer_Name__c = matchedSubCustomerName;
                        hasChanges = true;
                    }
                    
                    if (c.AccountId == null) {
                        caseUpdate.AccountId = matchedSubCustomerId;
                        caseUpdate.SubCustomer_Match__c = true;
                        hasChanges = true;
                    } else if (c.AccountId == matchedSubCustomerId) {
                        if (c.SubCustomer_Match__c != true) {
                            caseUpdate.SubCustomer_Match__c = true;
                            hasChanges = true;
                        }
                    } else {
                        if (c.SubCustomer_Match__c != false) {
                            caseUpdate.SubCustomer_Match__c = false;
                            hasChanges = true;
                        }
                    }
                }
                
                if (hasChanges) {
                    casesToUpdate.add(caseUpdate);
                }
            }
            
            if (!casesToUpdate.isEmpty()) {
                update casesToUpdate;
            }
            
        } catch (Exception e) {
            System.debug('Routing Handler Error: ' + e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    // Case-insensitive rule evaluation
    private static Boolean evaluateRule(Routing_Rule__c rule, Case c, List<EmailMessage> emails) {
        if (rule == null) return false;
        
        String criteria = rule.Criteria__c;
        String operator = rule.Operator__c;
        String value = rule.Value__c != null ? rule.Value__c.toLowerCase() : '';
        String domainValue = rule.Domain__c != null ? rule.Domain__c.toLowerCase() : '';
        
        List<String> textsToCheck = new List<String>();
        
        if (criteria == 'Subject') {
            if (c.Subject != null) textsToCheck.add(c.Subject);
            for (EmailMessage em : emails) if (em.Subject != null) textsToCheck.add(em.Subject);
        }
        else if (criteria == 'From Address') {
            if (c.SuppliedEmail != null) textsToCheck.add(c.SuppliedEmail);
            for (EmailMessage em : emails) if (em.FromAddress != null) textsToCheck.add(em.FromAddress);
        }
        else if (criteria == 'To Address') {
            for (EmailMessage em : emails) if (em.ToAddress != null) textsToCheck.add(em.ToAddress);
        }
        else if (criteria == 'CC Address') {
            for (EmailMessage em : emails) if (em.CcAddress != null) textsToCheck.add(em.CcAddress);
        }
        else if (criteria == 'Text Body' || criteria == 'Body') {
            if (c.Description != null) textsToCheck.add(c.Description);
            for (EmailMessage em : emails) if (em.TextBody != null) textsToCheck.add(em.TextBody);
        }
        else if (criteria == 'Domain') {
            if (c.SuppliedEmail != null) textsToCheck.add(parseDomain(c.SuppliedEmail));
            for (EmailMessage em : emails) if (em.FromAddress != null) textsToCheck.add(parseDomain(em.FromAddress));
            value = domainValue;
        }
        
        for (String text : textsToCheck) {
            if (String.isBlank(text)) continue;
            String lowerText = text.toLowerCase().trim();
            
            if (operator == 'Equals')              { if (lowerText == value) return true; }
            else if (operator == 'Not Equal To')   { if (lowerText != value) return true; }
            else if (operator == 'Contains')       { if (lowerText.contains(value)) return true; }
            else if (operator == 'Does Not Contain'){ if (!lowerText.contains(value)) return true; }
            else if (operator == 'Starts With')    { if (lowerText.startsWith(value)) return true; }
            else if (operator == 'Ends With')      { if (lowerText.endsWith(value)) return true; }
        }
        
        return false;
    }
    
    private static String parseDomain(String email) {
        if (String.isBlank(email) || !email.contains('@')) return '';
        return email.substringAfter('@').toLowerCase().trim();
    }
}