unpackaged/main/default/objects/NFTriggerSettings__c/NFTriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls the trigger settings to disable the trigger</description>
    <label>NFTriggerSettings</label>
</CustomObject>

unpackaged/main/default/objects/NFTriggerSettings__c/fields/OutboundSMS_Disable__c.field-meta.xml
<CustomField>
    <fullName>OutboundSMS_Disable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OutboundSMS_Disable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/OutboundSMS__c/OutboundSMS__c.object-meta.xml
<CustomObject>
    <description>custom object to house outbound SMS information from any object</description>
    <label>OutboundSMS</label>
    <nameField>
        <displayFormat>SMS-{0000000000}</displayFormat>
        <label>OutboundSMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OutboundSMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/OutboundSMS__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OutboundSMSHandler.cls
public class OutboundSMSHandler {
    
    public void run(){
        NFTriggerSettings__c triggerSetting =   NFTriggerSettings__c.getInstance();
        
        if(triggerSetting !=null && !triggerSetting.OutboundSMS_Disable__c ){
            if (Trigger.isAfter) {
                if (Trigger.isInsert) {
                    handleAfterInsert(Trigger.new);
                    
                } else if (Trigger.isUpdate) {
                    handleAfterUpdate(Trigger.new,Trigger.oldMap);
                }
            }
        }else{
            System.debug('Trigger is disabled by custom setting.'); 
        }
    }
    
    public void handleAfterInsert(List<OutboundSMS__c> newRecords){
        List<OutboundSMS__c> recordsToProcess = new List<OutboundSMS__c>();
        OutboundSMSService service = new OutboundSMSService();
        
        for (OutboundSMS__c sms : newRecords) {
            if(sms.Status__c == 'Queued'){
                recordsToProcess.add(sms);
            }
        }
        
        if (!recordsToProcess.isEmpty()) {
            service.processSMS(recordsToProcess);
        }
    }
    
    public void handleAfterUpdate(List<OutboundSMS__c> newRecords , Map<Id,Object > oldRecordsMap){
        Map<Id,OutboundSMS__c> oldMap = ( Map<Id,OutboundSMS__c>)oldRecordsMap;
        List<OutboundSMS__c> recordsToProcess = new List<OutboundSMS__c>();
        OutboundSMSService service = new OutboundSMSService();
        
        for (OutboundSMS__c sms : newRecords) {
            OutboundSMS__c oldSms = oldMap.get(sms.Id);
            if (oldSms.Status__c != 'Queued' && sms.Status__c == 'Queued') {
                recordsToProcess.add(sms);
            }
        }
        if (!recordsToProcess.isEmpty()) {
            service.processSMS(recordsToProcess);
        }
    }
}